// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Accountrole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

type Clinic struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	ClinicName  string         `json:"clinic_name"`
	Address     sql.NullString `json:"address"`
	PhoneNumber sql.NullString `json:"phone_number"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Examination struct {
	ID               uuid.UUID       `json:"id"`
	PatientID        uuid.UUID       `json:"patient_id"`
	ClinicID         uuid.UUID       `json:"clinic_id"`
	ExaminationsType string          `json:"examinations_type"`
	ExaminationData  json.RawMessage `json:"examination_data"`
	CreatedAt        sql.NullTime    `json:"created_at"`
}

type Patient struct {
	ID          uuid.UUID    `json:"id"`
	FirstName   string       `json:"first_name"`
	LastName    string       `json:"last_name"`
	DateOfBirth time.Time    `json:"date_of_birth"`
	NationalID  string       `json:"national_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	RoleName    string         `json:"role_name"`
	Description sql.NullString `json:"description"`
}

type User struct {
	ID        uuid.UUID    `json:"id"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}
